### PR TITLE
Add SOICbite to SWD adaptor board

### PR DESCRIPTION
**Pull request by urish**
The board features 4 connectors:

1. 8-pin IDC header for connecting to SOICbite
2. SMD Cortex-M Debug Connector
3. Though-hole Cortex-M Debug Connector
4. 4-Pin 2.54" connector breaking out the most common pins (VCC, GND, SWDIO, SWCLK). It can be used for connecting to ST-Link V2 programmer, or just for supplying power to the target board through the SOICbite port.

image

I have sent a batch of these boards to [OSH Park](https://www.oshpark.com) for manufacturing, and will report here after receiving, assembling and testing the boards.

### CODE REVIEW

**Comment by SimonMerrett** [comment]
Looking good! When I'm back at the computer I will review the PR. BTW what program did you use to make that render? It looks really cool.

**Comment by urish** [comment]
Thanks! I used KiCad's 3D Viewer with Raytracing enabled

**Comment by SimonMerrett** [comment]
Ah, I must turn ray tracing on!

**Comment by urish** [comment]
Update - I have received the board and assembled it, seem to be working properly (tested with ST-LINK mini):

image

So from my end, the PR is ready for merging

**Comment by SimonMerrett** [comment]
Sorry it took so long. Do you think we should add nrst to the suggested SWD pinout in the readme.md?

**Comment by urish** [comment]
Thanks for merging! 

Yes, I think adding that would make sense. 

In my own designs, I usually connect the BOOT0 pin as well (only relevant for STM32), I use pin 2 for that (arbitrary choice). The NRST seems generic enough to be added to the suggested pin-out, I'm not so sure about the BOOT0.

**Comment by urish** [comment]
p.s. should I add images of the board (or a 3D render) as well?

**Comment by SimonMerrett** [comment]
yes please to both!

**Comment by urish** [comment]
Here we go #10

**Pull request merged**
