### PR TITLE
SOICbite_USB Adaptor Board

### PR DESCRIPTION
**Pull request by DefProc**
as in #6 the USB adaptor board is tested working, and a plain UART board is included pending physical tests once the board is fabbed.

### CODE REVIEW

**Comment by SimonMerrett** [comment]
Thank you for taking the care to generate this PR. 👍 
I have checked the USB schematic, which looks fine to me in general. The only query I had from a "standardisation" perspective (rather than "it works as-is") is whether we want to move the ID pin to e.g. SOICbite pin 8, so that if the clip was attached the wrong way round, we wouldn't see 5V injected into the ID net. I haven't looked into the USB spec wrt the ID pin but I understand it expects to be either floating or tied to GND, so may not be able to take 5V on some devices.

Also, how long do you think it will be before you can test the UART board? I ask because I wonder if it's worth waiting and including as a final design in this PR, or whether to remove the WIP from this PR (I don't know how that would work/impact your fork, so I may be talking nonsense) until tested.

Thanks again!

**Comment by DefProc** [comment]
Good point. I'm expecting the uarts board shortly, but it shouldn't be part of this pull request. I've realised the better way to do it: It's now in a wip_uart branch in my repo, so it can be included separately when it's tested

**Comment by DefProc** [comment]
Sounds good. I left it floating on the board I used this with, but that does seem like a sensible pin change. I'll adjust that, re-do the board, and also add the pinout table. :smile:

**Comment by DefProc** [comment]
I've also changed the pinout to put D- next to Vcc. At least then it matches *every* USB port pinout! (my oversight) :open_mouth:

PCB silkscreen is updated to rev2, to indicate the change. 

rev2_3D_front

**Comment by DefProc** [comment]
I've also changed the pinout to put D- next to Vcc. At least then it matches every USB port pinout! (my oversight) :open_mouth:

PCB silkscreen is updated to rev2, to indicate the change.



I'm unlikely to make any more boards with this pinout in the short term — my connected board uses the rev1 pinout — so I'm unlikely to spin up this board immediately. I'm not sure if you'd prefer to wait until there's a physical build with this pinout? 

I'm happy to move this out to a WIP branch and open a separate PR if you'd rather wait before merging.

**Comment by SimonMerrett** [comment]
Thanks for all the changes you made!

**Pull request merged**
